; █▀▄▀█ █▀█ █▀▄ █░█ █░░ █▀▀ █▀
; █░▀░█ █▄█ █▄▀ █▄█ █▄▄ ██▄ ▄█

[module/pad]
type = custom/text
format = "   "

[module/polywins]
type = custom/script
exec = ~/.config/bspwm/polybar/scripts/polywins.sh 2>/dev/null
format = <label>
format-background = ${colors.background}
label = %output%
label-padding = 0
tail = true

; [module/launcher]
; type = custom/text
; ; format = "󱗆 "
; format = " "
; format-font = 5
; format-foreground = ${colors.color4}
; format-background = ${colors.background}
;
; click-left = dmenu_hub
; click-right = dmenu_hub

; [module/currency]
; format = <label>
; label = %{F#dfae67} %{F#A0A8CD}%output%
; type = custom/script
; exec = "cat ~/.cache/cash/rate"
; interval=600

[module/bspwm]
type = internal/bspwm

enable-click = true
pin-workspaces = true

format = <label-state>
format-font = 1

ws-icon-default = 󰊠

label-focused = 󰮯
label-focused-padding = 1
label-focused-foreground = ${colors.color2}
label-focused-background = ${colors.background}
label-focused-font = 1

label-occupied = 󰊠
label-occupied-padding = 1
label-occupied-foreground= ${colors.color3}
label-occupied-background = ${colors.background}
label-occupied-font = 1

label-urgent = %icon%
label-urgent-foreground = #88C0D0
label-urgent-background = ${colors.background}
label-urgent-padding = 4

label-empty = 󰊠
label-empty-foreground = ${colors.color7}
label-empty-background = ${colors.background}
label-empty-font = 1
label-empty-padding = 1

[bar]
fill = ""
empty = ""
indicator ="󱓻"
width = 8
format = %{T1}%fill%%indicator%%empty%%{F-}%{T-}

[module/alsa]
type = internal/alsa
format-volume = <label-volume> <bar-volume>
format-volume-background = ${colors.background}
label-volume-foreground = ${colors.color4}
format-muted-foreground = ${colors.foreground}
format-muted-background = ${colors.background}
label-muted = "  Muted"
label-volume = "󰎈 "

format-muted-padding = 1

bar-volume-format = ${bar.format}
bar-volume-width = ${bar.width}
bar-volume-gradient = false
bar-volume-indicator = ${bar.indicator}
bar-volume-indicator-foreground = ${colors.foreground}
bar-volume-fill = ${bar.fill}
bar-volume-foreground-0 = ${colors.color2}
bar-volume-foreground-1 = ${colors.color2}
bar-volume-foreground-2 = ${colors.color3}
bar-volume-foreground-3 = ${colors.color1}
bar-volume-empty = ${bar.empty}
bar-volume-empty-foreground = ${colors.foreground}

[module/time]
type = internal/date
interval = 60

format = <label>
format-background = ${colors.background}
format-foreground = ${colors.color4}

date =󰥔  %I:%M %P%{F-}
time-alt = 󰃭  %a, %b %d%{F-}

label = %date%%time%

[module/powermenu]
type = custom/text
format =" "
format-padding = 2
click-left = sysact &
format-foreground = ${colors.color1}

[module/wlan]
type = internal/network
interface = wlp1s0
interval = 3.0
format-connected =  <label-connected>
label-connected = "󰤪 %{A1:networkmanager_dmenu &:} %essid%%{A}"
label-connected-foreground = ${colors.color2}
label-connected-background = ${colors.background}
label-disconnected = "󰤭 %{A1:networkmanager_dmenu &:} Offline%{A}"
label-disconnected-foreground = ${colors.color3}
label-disconnected-background = ${colors.background}

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 99

format-charging = <animation-charging><label-charging>
label-charging = %percentage%%
format-charging-foreground = ${colors.color4}
format-charging-background = ${colors.background}
format-charging-padding = 1

format-discharging = <ramp-capacity><label-discharging>
label-discharging = %percentage%%
format-discharging-foreground = ${colors.foreground}
format-discharging-background = ${colors.background}
format-discharging-padding = 1

format-full-prefix = "  "
format-full-prefix-foreground = ${colors.color2}
format-foreground = ${colors.color4}
format-background = ${colors.background}
format-full-background = ${colors.background}
format-full-padding = 1

label-discharging-foreground = ${colors.foreground}
ramp-capacity-foreground = ${colors.color2}
label-charging-foreground = ${colors.foreground}
label-charging-background = ${colors.background}

label-padding = 1

ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "  "

animation-charging-0 = "  "
animation-charging-1 = "  "
animation-charging-2 = "  "
animation-charging-3 = "  "
animation-charging-4 = "  "

animation-charging-foreground = ${colors.color3}
animation-charging-background = ${colors.background}
animation-charging-framerate = 750
