#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx \$XINITRC"

alias svn="svn --config-dir \"$XDG_CONFIG_HOME\"/subversion"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done
unset command

alias \
	be="fzf-fd \$HOME/.local/bin | xargs nvim" \
	ce="fzf-fd \$HOME/.config | xargs nvim" \
	cg="fzf-grep \$HOME/.config" \
	fe="fzf-fd \$(pwd) | xargs nvim" \
	fg="fzf-grep \$(pwd)"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

alias \
	ls="exa --icons --group-directories-first" \
	lss="lsd -lt --total-size --group-directories-first" \
	lsa="exa -a --icons --group-directories-first" \
	lsas="lsd -lAt --total-size --group-directories-first" \
	lst="exa -T --icons" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \
	cat="bat -pp"

alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	v="\$EDITOR" \
	p="pacman" \
	z="zathura" \
	x="exit"

alias \
	ref="shortcuts >/dev/null; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/shortcutrc ; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/zshnameddirrc" \
	weath="curl wttr.in | head -n -1 | cat" \
	weath2="curl v2.wttr.in | head -n -1 | cat"
