profile=gpu-hq

autofit-smaller=858x480 # Set min window size.
osd-font='Lucida Grande'
osd-font-size=18

# Because of using uosc and thumbfast script
osc=no
osd-bar=no
border=no

# Deband filter.
deband=yes # Default values are 1:64:16:48

# Deband parameters configuration.
deband-iterations=2 # Range 1-16.
deband-threshold=35 # Range 0-4096.
deband-range=20 # Range 1-64.
deband-grain=5 # Range 0-4096.

dither-depth=auto
volume=75 # Set volume to 75% on startup.
volume-max=100 # Set player max vol to 100%.
scale=ewa_lanczossharp

#Youtube videos in 360p or less.
ytdl-format=bestvideo[height<=?360]+bestaudio/best
