[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on  = [ "k" ]
run = "plugin --sync arrow --args=-1"
desc = "Move cursor up"

[[manager.prepend_keymap]]
on  = [ "j" ]
run = "plugin --sync arrow --args=1"
desc = "Move cursor down"

[[manager.prepend_keymap]]
on = [ "<Up>" ]
run = "plugin --sync arrow --args=-1"
desc = "Move cursor up"

[[manager.prepend_keymap]]
on = [ "<Down>" ]
run = "plugin --sync arrow --args=1"
desc = "Move cursor down"

[[manager.prepend_keymap]]
on   = [ "<Right>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"
