#!/bin/bash

bspc rule -r "*"

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5'
		((name++))
	done
}

workspaces
bspc desktop -f 1

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config window_gap 0
bspc config border_width 1
bspc config split_ratio 0.50
bspc config bottom_padding 21
bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config presel_feedback true

bspc config active_border_color "#be95ff"
bspc config focused_border_color "#be95ff"
bspc config normal_border_color "#37474f"
bspc config presel_feedback_color "#be95ff"

bspc rule -a nmtui state=floating sticky=on follow=off focus=on
bspc rule -a spterm state=floating sticky=on follow=off focus=on
bspc rule -a spmusic state=floating sticky=on follow=off focus=on
bspc rule -a Zathura state=tiled

xsetroot -cursor_name left_ptr &

pkill -x sxhkd
sxhkd -c "$XDG_CONFIG_HOME"/bspwm/sxhkdrc &
bash "$XDG_CONFIG_HOME"/bspwm/polybar/scripts/launch.sh
